api/urls.py
from django.urls import path

from . import authentication, inbox, author, comment, commented, \
    follow, image, like, liked, other, post


# urlpatterns contains all of the routes that this application supports routing for.
# this routes traffic from polls/ to the index function that we defined earlier in the views file.
#
# HACK fqids are represented with `path` it feels a bit dirty though
# TODO Better names?
app_name = "polls"
urlpatterns = [
    # Authors API
    # GET
    path('authors/',
         author.get_authors,
         name='get_authors'),

    # Single Author API
    # GET / PUT
    path('authors/<int:pk>',
         author.handle_author,
         name='get_author_serial'),

    # Followers API
    # GET
    path('authors/<int:pk>/followers',
         follow.get_followers,
         name='get_followers'),
    # GET / PUT / DELETE (only GET is remote)
    path('authors/<int:author_serial>/followers/<path:foreign_author_fqid>',
         follow.handle_follower,
         name='handle_followers'),

    # Follow Request API
    # POST
    # NOTE: Also handles likes
    path('authors/<int:serial>/inbox',
         inbox.recieve_in_inbox,
         name='send_to_inbox'),

    # Posts API
    # GET / DELETE / PUT
    path('authors/<int:author_serial>/posts/<int:post_serial>',
         post.handle_post,
         name='handle_post'),
    
    # GET / POST
    path('authors/<int:pk>/posts',
         post.handle_author_posts,
         name='handle_author_posts'),

    # Image Posts
    path('authors/<int:author_serial>/posts/<int:post_serial>/image',
         image.get_image,
         name='get_image'),
    path('posts/<int:fqid>/image',
         image.get_fqid_image,
         name='get_fqid_image'),

    # Comments API
    # NOTE Inbox handled under Follow Request API
    # GET
    path('authors/<int:author_serial>/posts/<int:post_serial>/comments',
         comment.get_post_comments,
         name="get_post_comments"),
    
    # GET
    path('authors/<int:author_serial>/post/<int:post_serial>/comment/<path:comment_fqid>',
         comment.get_specific_comment,
         name="get_fqid_comment"),
    # GET
    path('comment/<path:fqid>',
         comment.get_fqid_comment,
         name="get_fqid_comment"),

    # Commented API
    # NOTE: Commented includes the non-api URL of the relevant post
    # GET / POST
    path('authors/<int:pk>/commented',
         commented.handle_author_commented,
         name="handle_author_commented"),
    # GET
    path('authors/<path:fqid>/commented',
         commented.get_fqid_author_commented,
         name="get_fqid_author_commented"),
    # GET
    path('authors/<int:author>/commented/<int:comment>',
         commented.get_author_commented,
         name="get_author_commented"),
    # GET
    path('commented/<path:fqid>',
         commented.get_commented,
         name='get_commented'),

    # Likes API
    # NOTE: inbox handled under Follow Request API
    # GET
    path('authors/<int:author_serial>/posts/<int:post_serial>/likes',
         like.get_post_likes,
         name="get_post_likes"),
    # GET
    path('posts/<path:fqid>/likes',
         like.get_fqid_post_likes,
         name="get_fqid_post_likes"),
    # GET
    path('authors/<int:author>/posts/<int:post>/comments/<int:comment>/likes',
         like.get_comment_likes,
         name="get_comment_likes"),
    # GET
    path('liked/<path:like_fqid>',
         like.get_like,
         name="get_like"),       
    # Liked API 
    path('authors/<int:author_serial>/liked',
         liked.get_author_liked,
         name="get_author_liked"),
     path('authors/<int:author_serial>/all_liked', # extra API helper function
         liked.get_author_all_liked,
         name="get_author_all_liked"),
    path('authors/<int:author_serial>/liked/<int:like_serial>',
         liked.get_author_like,
         name="get_author_like"),
    path('authors/<path:author_fqid>/liked/',
         liked.get_fqid_author_liked,
         name="get_fqid_author_liked"),
    # NOTE last one in examples clone from Likes API
    # EXTRA PATHS NOT REQUIRED IN THE SPECS
    path('user/has_liked', 
         other.has_user_liked_post,
         name='has_user_liked_post'),
    path('user/unlike_post', 
         other.user_unlike_post,
         name='user_unlike_post'),
    path('authors/<int:pk>/github_posts',
         other.handle_author_github_posts,
         name='handle_author_github_posts'),
    path('authors/handle_like_post',
         inbox.handle_like_post,
         name="handle_like_post"),
    path('<path:fqid>/create-share',    # Share api
          other.SharePostView.as_view(),
          name='create_share'),
    path('authors/all_likes', # extra API helper function
         like.get_post_all_likes,
         name="get_post_all_likes"),
     
     path('authors/<int:author_serial>/posts/<int:post_serial>/all_comments', # extra API helper function
         comment.get_post_all_comments,
         name="get_post_all_comments"),
     # FQID Paths
         # GET
    path('authors/<path:fqid>',
         author.get_fqid_author,
         name='get_fqid_author'),

     # GET
    path('posts/<path:fqid>/comments',
         comment.get_fqid_post_comments,
         name="get_fqid_post_comments"),

     # GET
    path('posts/<path:fqid>',
         post.get_fqid_post,
         name='get_fqid_post'),
     # Auth stuff
     path('auth/',
          authentication.authenticate,
          name='authenticate'),
     # Auth stuff
     path('auth/test',
          authentication.test_authenticate,
          name='test_authenticate'),
]

honeydew/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import root_redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root_redirect),
    path('api/', include('api.urls', namespace='api')),
    path('login/', include('login.urls')),
    path('post/', include('post.urls', namespace='post')),
    path('stream/', include('stream.urls')),
    path('authors/', include('author_page.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('create/', create_post, name='create_post'), 
    path('type/', get_type, name='get_post_type'),
    path('', index, name='index'),
    path("<path:fqid>/delete/", delete_post, name="delete_post"),
    path("<path:fqid>/edit/", edit_post, name="edit_post"),
    path("<path:fqid>/edit/save/", save_edit, name="save_edit"),
    path("<path:fqid>/comment/create", create_comment, name="create_comment"),
    
]

stream/urls.py
from django.urls import path
from . import views

from django.shortcuts import render

urlpatterns = [
    path('', views.stream_home, name='stream-home'),
    path("post/<path:id>/", views.view_post, name="view_post"),
]

stream/models.py
from django.db import models

# Create your models here.

post/views.py
from datetime import datetime

from django.shortcuts import redirect, render, get_object_or_404

from api.inbox import push_to_followers, push_to_friends, push_to_owner
from api.serializers import PostSerializer, CommentSerializer
from honeydew.models import Post, Comment


# Create your views here.
def index(request):
    '''
    This function redirects users to a UI to select the type of post they want to make
    @param request: http POST request
    @return: redirect to content_type selection page
    '''

    content_types = Post.CONTENT_CHOICES
    return render(request, "post/post_type.html", {'content_types': content_types})

def get_type(request):
    '''
    This function redirects users to a UI to create a post
    @param request: http POST request
    @return: redirect to page to create post
    '''
    type = request.POST.get('content_type')
    post_types = Post.POST_CHOICES[:-1]  # NOTE Assumes that DELETED is last

    return render(request, "post/post_make.html", {'post_types': post_types,
                                                   'content_type': type})


def create_post(request):
    '''
    This function creates a new post object
    @param request: http POST request
    @return: redirect to stream
    '''
    print(request.POST)
    print(request.FILES)
    if request.method == 'POST':

        #handle images vs text
        content_type = request.POST.get('content_type')
        if content_type == "IMAGE":
            post_image = request.FILES.get('post_image')
            print(type(post_image))
            content = post_image.read()
        else:
            content = request.POST.get('content')


        post = Post.objects.create(
            author=request.user.author,
            title=request.POST.get('title'),
            description=request.POST.get('description'),
            content_type=content_type,
            content=content,
            visibility=request.POST.get('visibility')
        )
        post.save()

        # Send this new post to all Nodes connected to this Node.
        serializer = PostSerializer(post)
        if post.visibility == Post.FRIENDS:
            push_to_friends(serializer, request.user.author)
        else:
            push_to_followers(serializer, request.user.author)
    return redirect('stream-home')

def edit_post(request, fqid):
    '''
    This function redirects users to an edit post view
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post to be edited
    @return: redirect to post_edit page or stream
    '''
    if request.method == 'POST':
        post = get_object_or_404(Post, fqid=fqid)
        post = PostSerializer(post)
        post_types = Post.POST_CHOICES
        return render(request, 'post/post_edit.html' , {'post': post.data, 'post_types': post_types})
    else:
        return redirect('stream-home')

def delete_post(request, fqid):
    '''
    This function deleted a post
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post to be deleted
    @return: redirect to stream
    '''

    #TODO: Update to a Put function instead of POST (for images)
    post = get_object_or_404(Post, fqid=fqid)
    if request.method == "POST":
        original_visibility = Post.visibility
        post.visibility = Post.DELETED
        post.save()

        serializer = PostSerializer(post)
        push_to_friends(serializer, post.author) \
            if original_visibility == Post.FRIENDS\
            else push_to_followers(serializer, post.author)

        return redirect('stream-home')  # Redirect to stream home

def save_edit(request, fqid):
    '''
    This saves the edits made to a post
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post to be saved after an edit
    @return: redirect to stream to see updated post
    '''

    #handle images vs text
    content_type = request.POST.get('content_type')
    if content_type == "IMAGE":
        post_image = request.FILES.get('post_image')
        print(type(post_image))
        content = post_image.read()
    else:
        content = request.POST.get('content')

    post = get_object_or_404(Post, fqid=fqid)
    post.title=request.POST.get('title')
    post.description=request.POST.get('description')
    post.content=content
    post.visibility=request.POST.get('visibility')
    post.published = datetime.now()
    post.save()

    serializer = PostSerializer(post)

    push_to_friends(serializer, post.author) \
        if post.visibility == Post.FRIENDS\
        else push_to_followers(serializer, post.author)

    return redirect('stream-home')

def create_comment(request, fqid):
    '''
    This function creates a new comment object
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post that the comment was made on
    @return: redirect to the post's page
    '''
    post = get_object_or_404(Post, fqid=fqid)
    if request.method == 'POST':
        comment = Comment.objects.create(
            author=request.user.author,
            post=post,
            content_type=request.POST.get('content_type'),
            content=request.POST.get('content'),
        )
        comment.save()

    serializer = CommentSerializer(comment)
    push_to_owner(serializer, post.author)
    push_to_friends(serializer, post.author)\
        if post.visibility == Post.FRIENDS\
        else push_to_followers(serializer, post.author)

    return redirect('view_post', post.fqid)

stream/templates/stream/post_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{  csrf_token  }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post View</title>
    {% load static %}
    {% load filters %}
    <link rel="stylesheet" href="{% static 'stream/css/post_view.css' %}">
    <script src="{% static 'js/fetch_functions.js' %}"></script>
</head>

<body>

    <div class="topbar">
        <div class="menu" id="menu">
            <a href="{% url 'stream-home' %}" class="menu-item" id="streamButton">Stream</a>
            <a href="{% url 'post:index' %}" class="menu-item" id="postButton">Post</a>
            <a href="{% url 'view_author_profile' user.serial %}" class="menu-item" id="profileButton">Profile</a>
            <a href="{% url 'view_follow_requests' user.serial %}" class="menu-item" id="authButton">Friend Requests</a>
            <a href="{% url 'view_authors' %}" class="menu-item" id="authButton">Authors</a>
            <a href="{% url 'logoutRequest' %}" class="menu-item" id="logoutButton">Log Out</a>
        </div>
    </div>

    <h1 class="title">Post Details</h1>

    <div class="post-box">
        <div class="header">
            <span class="author">
                <a href="{% url 'view_author_profile' post.author.id %}">{{ post.author.displayName }}</a>
            </span>
            <span class="time-posted">{{ post.published }}</span>
            {% if mine %}
            <form method="POST" action="{% url 'post:edit_post' post.id %}" type="post">
                {% csrf_token %}
                <button class="edit_post" type="submit">Edit Post</button>
            </form>

            <form method="POST" action="{% url 'post:delete_post' post.id %}"
                onsubmit="return confirm('Do you want to delete this post?')">
                {% csrf_token %}
                <button class="delete_post" type="submit">Delete</button>
            </form>
            {% endif %}
        </div>

        <div class="separator"></div>
        <h3>{{ post.title }}</h3>
        <p>{{ post.description }}</p>

        <!-- Render markdown if it is a markdown post -->
        {% if post.contentType == "text/markdown" %}
        <p class="content">{{ post.content|safe }}</p>

        {% elif post.contentType == "image/png;base64" %}
        <img src="{{ post.content }}" alt="{{ post.description }}" style="max-width: 200px;">
        {% elif post.contentType == "image/jpeg;base64" %}
        <img src="{{ post.content }}" alt="{{ post.description }}" style="max-width: 200px;">
        {% elif post.contentType == "application/base64" %}
        <img src="{{ post.content }}" alt="{{ post.description }}" style="max-width: 200px;">

        {% else %}
        <div>{{ post.content|safe }}</div>
        {% endif %}

        <div class="footer">
            <button class="button likeButton" id="likeButton{{ post.id|custom_slugify }}">
                <ion-icon name="heart-outline" class="icon" aria-label="Like"></ion-icon> Like
                <span class="interaction-count"
                    id="likeCount{{ post.id|custom_slugify }}">{{post.likes|default:0}}</span>
            </button>
            <button class="button commentButton" id="commentButton" data-post-id="{{ post.id|custom_slugify }}">
                <ion-icon name="chatbox-outline" class="icon" aria-label="Comment"></ion-icon> Comment
                <span class="interaction-count">{{ comment_count }}</span>
            </button>
            <button class="button shareButton" id="shareButton" data-post-id="{{ post.id|custom_slugify }}">
                <ion-icon name="share-social-outline" class="icon" aria-label="Share"></ion-icon> Share
            </button>
            <button class="button copyButton" id="copyButton{{ post.id|custom_slugify }}" onclick="copyLink()">
                <ion-icon name="copy-outline" class="icon" aria-label="Copy"></ion-icon> Copy
            </button>
            {% if post.visibility == "FRIENDS" %}
            <input type="hidden" value="{{ post.id }}" id="post_link" data-id="{{ post.id }}">
            {% else %}
            <p><input type="hidden" value="You may not copy link of Friends Only Posts" id="post_link"
                    data-id="{{ post.id }}"></p>
            {% endif %}
            
        </div>
    </div>

    <!-- Share Modal -->
    <div id="shareModal" class="modal">
        <div class="modal-content">
            <!-- Button to close the modal -->
            <span class="close" id="closeModal">&times;</span>
            <h2>Share Post</h2>

            <!-- Share form, using POST method to send data to the 'api:create_share' route -->
            <form method="POST" action="{% url 'api:create_share' post.id %}" data-post-id="{{ post.id }}">
                {% csrf_token %}
                <input type="hidden" name="fqid" value="{{ user.fqid }}">
                <!-- Text area for adding comments to the post -->
                <textarea name="shareComment" id="shareComment"
                    placeholder=" Add your thoughts to this post..."></textarea>

                <button class="submit-button" id="submitShare">Share</button>
            </form>
        </div>
    </div>


    <!-- Comment Modal -->
    <div id="commentModal" class="modal">
        <div class="modal-content">
            <!-- Button to close the modal -->
            <span class="close" id="closeCommentModal">&times;</span>
            <h2>Add a Comment</h2>

            <!-- Comment form, using POST method to send data to the 'post:create_comment' route -->
            <form method="POST" action="{% url 'post:create_comment' post.id %}">
                {% csrf_token %}
                <textarea name="content" id="commentContent" placeholder="Write your comment here..."
                    required></textarea>
                <label for="content_type">Type:</label>
                <select id="commentContentType" name="content_type" required>
                    {% for value, label in content_types %}
                    <option value="{{value}}">{{label}}</option>
                    {% endfor %}
                </select>
                <button class="submit-button" id="submitComment">Submit Comment</button>
            </form>
        </div>
    </div>

    <h3>Comments</h3>
    {% for item in comments %}
    <div class="comment_box">
        <div class="header">
            <span class="author">
                <a href="{% url 'view_author_profile' item.author.id %}">{{ item.author.displayName }}</a>
            </span>
            <span class="time-posted">{{ item.published }}</span>
        </div>

        <!-- Render markdown if it is a markdown comment -->
        {% if item.contentType == "text/markdown" %}
        <p class="content">{{ item.comment }}</p>
        {% else %}
        <p>{{ item.comment }}</p>
        {% endif %}
    </div>
    {% endfor %}

    <script>

        // Gets posts, which are passed from views.py
        const post = {{ post | safe }} // Just a single post, to lazy to refactor

        /* 
          Add event listeners for each button in the post
        */
        async function attachPostEventListeners(post) {
            /*
                Create references to relavent componenets of a post. (UI and Post Model references)
            */
            postID = slugify(post.id)
            /* Get reference to each button in the post */
            const likeButton = document.querySelector(`#likeButton${postID}`);
            console.log("LIKE BUTTON", likeButton)

            /* Get Author of the Post */
            const authorFQID = post.author.id
            const authorFQIDList = post.author.id.split('/');
            const authorSerial = post.author.id.split('/')[authorFQIDList.length - 1]; // Ensure this is the correct path to the FQID

            /* Get Current user's serial */
            const userFQID = "{{ user.fqid }}"
            const userSerial = "{{ user.serial }}"

            /* Get Current Post's serial */
            const postFQID = post.id
            const postFQIDList = post.id.split('/');
            const postSerial = post.id.split('/')[postFQIDList.length - 1]; // Ensure this is the correct path to the FQID

            /* 
                Encode behaviour into each button in the post 
                By using Click Event Listeners
            */
            if (likeButton) {
                // Get like Count
                var interactionCount = document.querySelector(`#likeCount${postID}`); // Select the count span
                console.log("INTERACTION COUNT BUTTON", interactionCount)
                display_likes(authorFQID, postFQID, interactionCount)

                // Add Click listener for likes
                likeButton.addEventListener('click', async () => {
                    console.log("USER FQID: ", userFQID)
                    console.log("AUTHOR FQID: ", authorFQID)
                    console.log("POST FQID: ", postFQID)
                    // Create Like Object
                    let already_liked = await check_user_liked_post(userFQID, authorFQID, postFQID)
                    if (already_liked) {
                        console.log("Already Liked!")
                        await delete_like(userFQID, authorFQID, postFQID, interactionCount);
                        location.reload();
                    } else {
                        await like_post(userFQID, authorFQID, postFQID, interactionCount);
                        location.reload();
                    }

                });
            }

        }

        async function main() {
            // Entry point for our stream code
            await attachPostEventListeners(post);
        }

        // Entry point for our stream code
        main();

    </script>

    <script src="{% static 'markdown-renderer.min.js' %}"></script>
    <script src="{% static 'js/share.js' %}"></script>
    <script src="{% static 'js/comment.js' %}"></script>
    <script src="{% static 'js/fetch_functions.js' %}"></script>
    <script src="{% static 'js/formatTime.js' %}"></script>

    <!-- Import Ionic App Icons package -->
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

</body>

</html>

stream/templates/stream/stream.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  {% load filters %}
  <meta charset="UTF-8">
  <meta name="csrf-token" content="{{  csrf_token  }}">
  <title>Social Media Posts Widget</title>
  <link rel="stylesheet" href="{% static 'stream/css/stream.css' %}">
  <script src="{% static 'js/fetch_functions.js' %}"></script>
</head>

<body>
  <!-- Our Header/TopBar of the Stream Page. -->
  <div class="topbar">
    <div class="menu" id="menu">
      <a href="{% url 'post:index' %}" class="menu-item" id="postButton">Post</a>
      <a href="{% url 'view_author_profile' user.serial %}" class="menu-item" id="profileButton">Profile</a>
      <a href="{% url 'view_follow_requests' user.serial %}" class="menu-item" id="authButton">Friend Requests</a>
      <a href="{% url 'view_authors' %}" class="menu-item" id="authButton">Authors</a>
      <a href="{% url 'logoutRequest' %}" class="menu-item" id="logoutButton">Log Out</a>
    </div>
  </div>

  <h1 class="title">Posts Stream</h1>

  <!-- 
    Contains All Post Components in the User's Stream. 
    The Post Components are created in the function createPostBox
  -->
  <div class="box" id="postContainer">
    {% for post in posts %}
    <div class="post-box">
      <div class="header">
        <span class="author">
          <a href="{% url 'view_author_profile' post.author.id %}">{{ post.author.displayName }}</a>
        </span>
        <span class="time-posted">{{ post.published }}</span>
      </div>
      <div class="separator"></div>
      <h3>
        <a href="{% url 'view_post' post.id%}">{{ post.title }}</a>
      </h3>
      <p>{{ post.description }}</p>

      {% if post.contentType == "text/markdown" %}
      <p class="content">{{ post.content|safe }}</p>


      {% elif post.contentType == "image/png;base64" %}
      <img src="{{ post.content }}" alt="{{ post.description }}" style="max-width: 200px;">
      {% elif post.contentType == "image/jpeg;base64" %}
      <img src="{{ post.content }}" alt="{{ post.description }}" style="max-width: 200px;">
      {% elif post.contentType == "application/base64" %}
      <img src="{{ post.content }}" alt="{{ post.description }}" style="max-width: 200px;">

      {% else %}
      <p>{{ post.content|safe }}</p>
      {% endif %}

      <div class="footer">
        <button class="button likeButton" id="likeButton{{ post.id|custom_slugify }}">
          <ion-icon name="heart-outline" class="icon" aria-label="Like"></ion-icon> Like
          <span class="interaction-count" id="likeCount{{ post.id|custom_slugify }}">{{post.likes|default:0}}</span>
        </button>
        <a href="{% url 'view_post' post.id %}">
          <button class="button commentButton" id="commentButton{{ post.id|custom_slugify }}">
            <ion-icon name="chatbox-outline" class="icon" aria-label="Comment"></ion-icon> Comment
            <span class="interaction-count"
              id="commentCount{{ post.id|custom_slugify }}">{{post.comments|default:0}}</span>
          </button>
        </a>

        {% if post.visibility != "FRIENDS" %}
        <input type="hidden" value="{{ post.id }}" id="post_link" data-id="{{ post.id }}">
        {% else %}
        <p><input type="hidden" value="You may not copy link of Friends Only Posts" id="post_link"
            data-id="{{ post.id }}"></p>
        {% endif %}
        <button class="button copyButton" id="copyButton{{ post.id|custom_slugify }}" onclick="copyLink()">
          <ion-icon name="copy-outline" class="icon" aria-label="Copy"></ion-icon> Copy
        </button>
      </div>
    </div>

    {% endfor %}
  </div>
  <div class="pagination"> <!-- Credit: https://stackoverflow.com/a/74619754 -->
      <span>
          <!-- Display Previous Page Options -->
          {% if page_obj.has_previous %}
              <!-- Reload the stream, but with new parameters (page)-->
              <a href="?page=1">First</a>  
              <a href="?page={{ page_obj.previous_page_number }}">Previous</a>   
          {% endif %}
          <!-- Display Page number -->
          <span>
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </span>
          <!-- Display Next Page Options -->
          {% if page_obj.has_next %}
              <!-- Reload the stream, but with new parameters (page)-->
              <a href="?page={{ page_obj.next_page_number }}">Next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          {% endif %}
      </span>
  </div>


  <script>
    async function display_comments(authorSerial, postSerial, interactionCount) {
      try {
        console.log("in display comments");
        const response = await fetch(`/api/authors/${authorSerial}/posts/${postSerial}/all_comments`, {
          method: 'GET',
        });

        if (!response.ok) {
          throw new Error(`Error getting Post Comments! Status: ${response.status}`);
        }

        const data = await response.json(); // Parse the JSON from the response
        interactionCount.textContent = data.count || 0; // Update interaction count
        return data; // Return the data if needed elsewhere
      } catch (error) {
        console.error(error.message); // Log the error to the console
      }
    }

    // Gets posts, which are passed from views.py
    const posts = {{ posts | safe }};

    /* 
      Add event listeners for each individual post 
      Every like/comment/share button is uniquely assigned it's own event listener,
      by Mapping Each button to an new event listener  
    */
    async function attachPostEventListeners(posts) {
      /* For each post */
      posts.forEach(post => {
        /*
          Create references to relavent componenets of a post. (UI and Post Model references)
        */
        postID = slugify(post.id)
        /* Get reference to each button in the post */
        const likeButton = document.querySelector(`#likeButton${postID}`);
        const commentButton = document.querySelector(`#commentButton${postID}`);
        const commentModal = document.getElementById("commentModal");
        const closeModal = document.getElementById('closeCommentModal');

        /* Get Author of the Post */
        const authorFQID = post.author.id
        const authorFQIDList = post.author.id.split('/');
        const authorSerial = post.author.id.split('/')[authorFQIDList.length - 1]; // Ensure this is the correct path to the FQID

        /* Get Current user's serial */
        const userFQID = "{{ user.fqid }}"
        const userSerial = "{{ user.serial }}"

        /* Get Current Post's serial */
        const postFQID = post.id
        const postFQIDList = post.id.split('/');
        const postSerial = post.id.split('/')[postFQIDList.length - 1]; // Ensure this is the correct path to the FQID

        /* 
          Encode behaviour into each button in the post 
          By using Click Event Listeners
        */
        if (likeButton) {
          // Get like Count
          var interactionCount = document.querySelector(`#likeCount${postID}`); // Select the count span

          display_likes(authorFQID, postFQID, interactionCount)

          // Add Click listener for likes
          likeButton.addEventListener('click', async () => {
            console.log("LISTENER")
            console.log("USER FQID: ", userFQID)
            console.log("AUTHOR FQID: ", authorFQID)
            console.log("POST FQID: ", postFQID)
            // Create Like Object
            let already_liked = await check_user_liked_post(userFQID, authorFQID, postFQID)
            if (already_liked) {
              console.log("Already Liked!")
              await delete_like(userFQID, authorFQID, postFQID, interactionCount);
            } else {
              console.log("Liking Post!")
              await like_post(userFQID, authorFQID, postFQID, interactionCount);
            }

          });
        }

        if (commentButton) {
          var interCount = document.querySelector(`#commentCount${postID}`); // Select the count span

          display_comments(authorSerial, postSerial, interCount)
        }

      });
    }

    async function main() {
      // Entry point for our stream code
      await attachPostEventListeners(posts);
      await fetch_activity("{{user.serial}}", "{{user.github}}");
    }

    // Entry point for our stream code
    main();

  </script>

  <!-- Render Markdown Content -->
  <script src="{% static 'markdown-renderer.min.js' %}"></script>

  <!-- Import Ionic App Icons package https://ionic.io/ionicons -->
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  <script src="{% static 'js/formatTime.js' %}"></script>
</body>

</html>