api/urls.py
from django.urls import path

from . import authentication, inbox, author, comment, commented, \
    follow, image, like, liked, other, post


# urlpatterns contains all of the routes that this application supports routing for.
# this routes traffic from polls/ to the index function that we defined earlier in the views file.
#
# HACK fqids are represented with `path` it feels a bit dirty though
# TODO Better names?
app_name = "polls"
urlpatterns = [
    # Authors API
    # GET
    path('authors/',
         author.get_authors,
         name='get_authors'),

    # Single Author API
    # GET / PUT
    path('authors/<int:pk>',
         author.handle_author,
         name='get_author_serial'),

    # Followers API
    # GET
    path('authors/<int:pk>/followers',
         follow.get_followers,
         name='get_followers'),
    # GET / PUT / DELETE (only GET is remote)
    path('authors/<int:author_serial>/followers/<path:foreign_author_fqid>',
         follow.handle_follower,
         name='handle_followers'),

    # Follow Request API
    # POST
    # NOTE: Also handles likes
    path('authors/<int:serial>/inbox',
         inbox.recieve_in_inbox,
         name='send_to_inbox'),

    # Posts API
    # GET / DELETE / PUT
    path('authors/<int:author_serial>/posts/<int:post_serial>',
         post.handle_post,
         name='handle_post'),
    
    # GET / POST
    path('authors/<int:pk>/posts',
         post.handle_author_posts,
         name='handle_author_posts'),

    # Image Posts
    path('authors/<int:author_serial>/posts/<int:post_serial>/image',
         image.get_image,
         name='get_image'),
    path('posts/<int:fqid>/image',
         image.get_fqid_image,
         name='get_fqid_image'),

    # Comments API
    # NOTE Inbox handled under Follow Request API
    # GET
    path('authors/<int:author_serial>/posts/<int:post_serial>/comments',
         comment.get_post_comments,
         name="get_post_comments"),
    
    # GET
    path('authors/<int:author_serial>/post/<int:post_serial>/comment/<path:comment_fqid>',
         comment.get_specific_comment,
         name="get_fqid_comment"),
    # GET
    path('comment/<path:fqid>',
         comment.get_fqid_comment,
         name="get_fqid_comment"),

    # Commented API
    # NOTE: Commented includes the non-api URL of the relevant post
    # GET / POST
    path('authors/<int:pk>/commented',
         commented.handle_author_commented,
         name="handle_author_commented"),
    # GET
    path('authors/<path:fqid>/commented',
         commented.get_fqid_author_commented,
         name="get_fqid_author_commented"),
    # GET
    path('authors/<int:author>/commented/<int:comment>',
         commented.get_author_commented,
         name="get_author_commented"),
    # GET
    path('commented/<path:fqid>',
         commented.get_commented,
         name='get_commented'),

    # Likes API
    # NOTE: inbox handled under Follow Request API
    # GET
    path('authors/<int:author_serial>/posts/<int:post_serial>/likes',
         like.get_post_likes,
         name="get_post_likes"),
    # GET
    path('posts/<path:fqid>/likes',
         like.get_fqid_post_likes,
         name="get_fqid_post_likes"),
    # GET
    path('authors/<int:author>/posts/<int:post>/comments/<int:comment>/likes',
         like.get_comment_likes,
         name="get_comment_likes"),
    # GET
    path('liked/<path:like_fqid>',
         like.get_like,
         name="get_like"),       
    # Liked API 
    path('authors/<int:author_serial>/liked',
         liked.get_author_liked,
         name="get_author_liked"),
     path('authors/<int:author_serial>/all_liked', # extra API helper function
         liked.get_author_all_liked,
         name="get_author_all_liked"),
    path('authors/<int:author_serial>/liked/<int:like_serial>',
         liked.get_author_like,
         name="get_author_like"),
    path('authors/<path:author_fqid>/liked/',
         liked.get_fqid_author_liked,
         name="get_fqid_author_liked"),
    # NOTE last one in examples clone from Likes API
    # EXTRA PATHS NOT REQUIRED IN THE SPECS
    path('user/has_liked', 
         other.has_user_liked_post,
         name='has_user_liked_post'),
    path('user/unlike_post', 
         other.user_unlike_post,
         name='user_unlike_post'),
    path('authors/<int:pk>/github_posts',
         other.handle_author_github_posts,
         name='handle_author_github_posts'),
    path('authors/handle_like_post',
         inbox.handle_like_post,
         name="handle_like_post"),
    path('<path:fqid>/create-share',    # Share api
          other.SharePostView.as_view(),
          name='create_share'),
    path('authors/all_likes', # extra API helper function
         like.get_post_all_likes,
         name="get_post_all_likes"),
     
     path('authors/<int:author_serial>/posts/<int:post_serial>/all_comments', # extra API helper function
         comment.get_post_all_comments,
         name="get_post_all_comments"),
     # FQID Paths
         # GET
    path('authors/<path:fqid>',
         author.get_fqid_author,
         name='get_fqid_author'),

     # GET
    path('posts/<path:fqid>/comments',
         comment.get_fqid_post_comments,
         name="get_fqid_post_comments"),

     # GET
    path('posts/<path:fqid>',
         post.get_fqid_post,
         name='get_fqid_post'),
     # Auth stuff
     path('auth/',
          authentication.authenticate,
          name='authenticate'),
     # Auth stuff
     path('auth/test',
          authentication.test_authenticate,
          name='test_authenticate'),
]

honeydew/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import root_redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root_redirect),
    path('api/', include('api.urls', namespace='api')),
    path('login/', include('login.urls')),
    path('post/', include('post.urls', namespace='post')),
    path('stream/', include('stream.urls')),
    path('authors/', include('author_page.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('create/', create_post, name='create_post'), 
    path('type/', get_type, name='get_post_type'),
    path('', index, name='index'),
    path("<path:fqid>/delete/", delete_post, name="delete_post"),
    path("<path:fqid>/edit/", edit_post, name="edit_post"),
    path("<path:fqid>/edit/save/", save_edit, name="save_edit"),
    path("<path:fqid>/comment/create", create_comment, name="create_comment"),
    
]

post/views.py
from datetime import datetime

from django.shortcuts import redirect, render, get_object_or_404

from api.inbox import push_to_followers, push_to_friends, push_to_owner
from api.serializers import PostSerializer, CommentSerializer
from honeydew.models import Post, Comment


# Create your views here.
def index(request):
    '''
    This function redirects users to a UI to select the type of post they want to make
    @param request: http POST request
    @return: redirect to content_type selection page
    '''

    content_types = Post.CONTENT_CHOICES
    return render(request, "post/post_type.html", {'content_types': content_types})

def get_type(request):
    '''
    This function redirects users to a UI to create a post
    @param request: http POST request
    @return: redirect to page to create post
    '''
    type = request.POST.get('content_type')
    post_types = Post.POST_CHOICES[:-1]  # NOTE Assumes that DELETED is last

    return render(request, "post/post_make.html", {'post_types': post_types,
                                                   'content_type': type})


def create_post(request):
    '''
    This function creates a new post object
    @param request: http POST request
    @return: redirect to stream
    '''
    print(request.POST)
    print(request.FILES)
    if request.method == 'POST':

        #handle images vs text
        content_type = request.POST.get('content_type')
        if content_type == "IMAGE":
            post_image = request.FILES.get('post_image')
            print(type(post_image))
            content = post_image.read()
        else:
            content = request.POST.get('content')


        post = Post.objects.create(
            author=request.user.author,
            title=request.POST.get('title'),
            description=request.POST.get('description'),
            content_type=content_type,
            content=content,
            visibility=request.POST.get('visibility')
        )
        post.save()

        # Send this new post to all Nodes connected to this Node.
        serializer = PostSerializer(post)
        if post.visibility == Post.FRIENDS:
            push_to_friends(serializer, request.user.author)
        else:
            push_to_followers(serializer, request.user.author)
    return redirect('stream-home')

def edit_post(request, fqid):
    '''
    This function redirects users to an edit post view
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post to be edited
    @return: redirect to post_edit page or stream
    '''
    if request.method == 'POST':
        post = get_object_or_404(Post, fqid=fqid)
        post = PostSerializer(post)
        post_types = Post.POST_CHOICES
        return render(request, 'post/post_edit.html' , {'post': post.data, 'post_types': post_types})
    else:
        return redirect('stream-home')

def delete_post(request, fqid):
    '''
    This function deleted a post
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post to be deleted
    @return: redirect to stream
    '''

    #TODO: Update to a Put function instead of POST (for images)
    post = get_object_or_404(Post, fqid=fqid)
    if request.method == "POST":
        original_visibility = Post.visibility
        post.visibility = Post.DELETED
        post.save()

        serializer = PostSerializer(post)
        push_to_friends(serializer, post.author) \
            if original_visibility == Post.FRIENDS\
            else push_to_followers(serializer, post.author)

        return redirect('stream-home')  # Redirect to stream home

def save_edit(request, fqid):
    '''
    This saves the edits made to a post
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post to be saved after an edit
    @return: redirect to stream to see updated post
    '''

    #handle images vs text
    content_type = request.POST.get('content_type')
    if content_type == "IMAGE":
        post_image = request.FILES.get('post_image')
        print(type(post_image))
        content = post_image.read()
    else:
        content = request.POST.get('content')

    post = get_object_or_404(Post, fqid=fqid)
    post.title=request.POST.get('title')
    post.description=request.POST.get('description')
    post.content=content
    post.visibility=request.POST.get('visibility')
    post.published = datetime.now()
    post.save()

    serializer = PostSerializer(post)

    push_to_friends(serializer, post.author) \
        if post.visibility == Post.FRIENDS\
        else push_to_followers(serializer, post.author)

    return redirect('stream-home')

def create_comment(request, fqid):
    '''
    This function creates a new comment object
    @param request: http POST request
    @param fqid: the fqid (unique URL) of the post that the comment was made on
    @return: redirect to the post's page
    '''
    post = get_object_or_404(Post, fqid=fqid)
    if request.method == 'POST':
        comment = Comment.objects.create(
            author=request.user.author,
            post=post,
            content_type=request.POST.get('content_type'),
            content=request.POST.get('content'),
        )
        comment.save()

    serializer = CommentSerializer(comment)
    push_to_owner(serializer, post.author)
    push_to_friends(serializer, post.author)\
        if post.visibility == Post.FRIENDS\
        else push_to_followers(serializer, post.author)

    return redirect('view_post', post.fqid)

post/templates/post/post_edit.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'post/css/post_make.css' %}">
    </head>
    <body>
        
        <form id="post-form" action="{% url 'post:save_edit' post.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>POST PAGE</h2>
            <input type="hidden" name="content_type" value="{{ post.contentType }}">
        
            <label for="title">Title:</label>
            <input type="text" id="title" name="title" value ="{{ post.title }}">
        
            <label for="description">Description:</label>
            <input type="text" id="description" name="description" value="{{ post.description }}">
            
            <p>Must upload a new image</p>
            {% if post.contentType == "image/jpeg;base64" %}
            <label for="post_image">Upload Image:</label>
            <input type="file" name="post_image" id="post_image">
            {% endif %}

            {% if post.contentType == "image/png;base64" %}
            <label for="post_image">Upload Image:</label>
            <input type="file" name="post_image" id="post_image">
            {% endif %}

            {% if post.contentType == "text/markdown" %}
            <label for="content">Content:</label>
            <textarea id="markdown-editor" rows="10" cols="50" name="content"
            required>  {{post.content}} </textarea>
            {% endif %}

            {% if post.contentType == "text/plain" %}
            <label for="content">Content:</label>
            <textarea id="content" rows="10" cols="50" name="content" required>
                {{post.content}} 
            </textarea>
            {% endif %}
        
            <label for="visibility">Visibility:</label>
            <select id="visibility" name="visibility">
                {% for value, label in post_types %}
                <option value="{{ value }}" {% if value == post.visibility %}selected{% endif %}>
                    {{ label }}
                </option>
                {% endfor %}
            </select>
        
            <button type="submit">Submit</button>
        </form>

        <script src="{% static 'markdown-editor.min.js' %}"></script>
           
        
    </body>
</html>

post/templates/post/post_img.html
{% extends 'post/post_make.html' %}

{% block content %}
<label for="post_image">Upload Image:</label>
                    <input type="file" name="post_image" id="post_image">
{% endblock %}

post/templates/post/post_make.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'post/css/post_make.css' %}">
    </head>
    <body>
        
        <form id="post-form" action="{% url 'post:create_post' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>POST PAGE</h2>
            <input type="hidden" name="content_type" value="{{ content_type }}">
        
            <label for="title">Title:</label>
            <input type="text" id="title" name="title" required>
        
            <label for="description">Description:</label>
            <input type="text" id="description" name="description" required>
        
            {% if content_type == "IMAGE" %}
            <label for="post_image">Upload Image:</label>
            <input type="file" name="post_image" id="post_image">
            {% endif %}

            {% if content_type == "text/markdown" %}
            <label for="content">Content:</label>
            <textarea id="markdown-editor" rows="10" cols="50" placeholder="Write your content here" name="content"
            required></textarea>
            {% endif %}

            {% if content_type == "text/plain" %}
            <label for="content">Content:</label>
            <textarea id="content" rows="10" cols="50" placeholder="Write your content here!" name="content" required></textarea>
            {% endif %}
        
            <label for="visibility">Visibility:</label>
            <select id="visibility" name="visibility" required>
                {% for value, label in post_types %}
                <option value = "{{value}}">{{label}}</option>
                {% endfor %}
            </select>
        
            <button type="submit">Submit</button>
        </form>

        <script src="{% static 'markdown-editor.min.js' %}"></script>
        <script>
            console.log(user)
        </script>
        
    </body>
    
</html>

post/templates/post/post_mark.html
{% extends 'post/post_make.html' %}

{% block content %}
<label for="content">Content:</label>
<textarea id="markdown-editor" rows="10" cols="50" placeholder="Write your content here" name="content"
    required></textarea>
{% endblock %}

{% block script %}
{% load static %}
<script src="{% static 'markdown-editor.min.js' %}"></script>
{% endblock %}

post/templates/post/post_plain.html
{% extends 'post/post_make.html' %}

{% block content %}
<label for="content">Content:</label>
            <textarea id="content" rows="10" cols="50" placeholder="Write your content here!" name="content" required></textarea>
{% endblock %}

post/templates/post/post_type.html
<!DOCTYPE html>
<hmtl>

    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'post/css/post_type.css' %}">
    </head>

    <body>
        <h1>What kind of post do you want to make?</h1>
        <form id="type-form" action="{% url 'post:get_post_type' %}" method="post">
            
            {% csrf_token %}

            <select id="content_type" name="content_type" required>
                {% for value, label in content_types %}
                <option value="{{value}}">{{label}}</option>
                {% endfor %}
            </select>

            <button type="submit">Next</button>
        </form>

        
    </body>
</hmtl>